services:

  app:
    image: zero2prod
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password