application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "https://api.sendgrid.com"
  sender_email: "prod@example.com"
